In [1]:
import pandas as pd
import numpy as np

In [2]:
use_cols = [
    'Sentiment', 'Tweet Id', 'Data & Time', 'Flag', 'User','Tweet'
]

tweets = pd.read_csv("training.csv", names = use_cols, encoding = 'latin-1')

In [3]:
tweets.head()

Sentiment    Tweet Id                   Data & Time      Flag  \
0          0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1          0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2          0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3          0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4          0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   

              User                                              Tweet  
0  _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1    scotthamilton  is upset that he can't update his Facebook by ...  
2         mattycus  @Kenichan I dived many times for the ball. Man...  
3          ElleCTF    my whole body feels itchy and like its on fire   
4           Karoli  @nationwideclass no, it's not behaving at all....

In [4]:
sentiment = tweets.Sentiment.unique()
print(sentiment)

## 0 stands for negative and 4 stands for positive and 2 for neutral
## as we can see that there is no neutral tweet in th dataset

[0 4]


In [5]:
## count for every sentiment in the dataset 
tweets.groupby("Sentiment").count()

Tweet Id  Data & Time    Flag    User   Tweet
Sentiment                                               
0            800000       800000  800000  800000  800000
4            800000       800000  800000  800000  800000

In [6]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyser = SentimentIntensityAnalyzer()

In [24]:
def sentiment_analyzer_scores(sentence):
    score = analyser.polarity_scores(sentence)
    ## print(type(score))
    ## print(score)
    ## print(score["compound"])
    return score["compound"]

In [9]:
test_str = tweets.iloc[0,5]
print(test_str)

@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer.  You shoulda got David Carr of Third Day to do it. ;D


In [26]:
x = sentiment_analyzer_scores(test_str)
print(x)

-0.0173


In [27]:
predicted_sentiments = []

for i in range(0,len(tweets)):
    str = tweets.iloc[i,5]
    rating = sentiment_analyzer_scores(str)
    if rating <= -0.05:
        predicted_sentiments.append(0)
    elif rating >= 0.05:
        predicted_sentiments.append(4)
    else: 
        predicted_sentiments.append(2)

In [29]:
tweets['Predicted Sentiment'] = predicted_sentiments 

In [31]:
tweets.head()

Sentiment    Tweet Id                   Data & Time      Flag  \
0          0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1          0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2          0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3          0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4          0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   

              User                                              Tweet  \
0  _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...   
1    scotthamilton  is upset that he can't update his Facebook by ...   
2         mattycus  @Kenichan I dived many times for the ball. Man...   
3          ElleCTF    my whole body feels itchy and like its on fire    
4           Karoli  @nationwideclass no, it's not behaving at all....   

   Predicted Sentiment  
0                    2  
1                    0  
2                    4  
3                    0  
4                    0

In [35]:
incorrect = 0
for i in range(0,len(tweets)):
    true = tweets.iloc[i,0]
    pred = tweets.iloc[i,6]
    if true != pred:
        incorrect += 1

print("Error = %2.6f" %(incorrect/len(tweets)))
print("Accuracy = %2.6f" %((len(tweets)-incorrect)/len(tweets)))

Error = 0.482812
Accuracy = 0.517188


In [37]:
tweets.groupby("Predicted Sentiment").count()

Sentiment  Tweet Id  Data & Time    Flag    User   Tweet
Predicted Sentiment                                                          
0                       414852    414852       414852  414852  414852  414852
2                       443782    443782       443782  443782  443782  443782
4                       741366    741366       741366  741366  741366  741366

In [38]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [40]:
sentiment = list(tweets['Sentiment'])

results = confusion_matrix(sentiment, predicted_sentiments) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(sentiment, predicted_sentiments)) 
print('Report : ')
print(classification_report(sentiment, predicted_sentiments))

Confusion Matrix :
[[335347 215441 249212]
 [     0      0      0]
 [ 79505 228341 492154]]
Accuracy Score : 0.517188125
Report : 
             precision    recall  f1-score   support

          0       0.81      0.42      0.55    800000
          2       0.00      0.00      0.00         0
          4       0.66      0.62      0.64    800000

avg / total       0.74      0.52      0.60   1600000



C:\Users\Gurshaan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
